env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "4b9b953939869799"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"

command:
  - uvicorn
  - backend.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
